//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ELEarningSystemMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BookingTbl
    {
        public string name { get; set; }
        public string gender { get; set; }
        public string email { get; set; }
        public decimal mobile { get; set; }
        public string category { get; set; }
        public string courseName { get; set; }
        public System.DateTime joinDate { get; set; }
        public string description { get; set; }
    }
}
