//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ELEarningSystemMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblFeedback
    {
        public string name { get; set; }
        public string mail { get; set; }
        public string subjects { get; set; }
        public string messages { get; set; }
    }
}
